# Generated by Django 2.1.5 on 2021-12-19 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netfeelex',
            name='Date_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 21, 25, 5, 302326), verbose_name='Date publié'),
        ),
    ]
